### ISSUE TITLE
Disabled date ranges years/months selection

### ISSUE THREAD

**Issue by impetoyt** [WhatSock/apex#46]
ARIA DATE PICKER (WITH ABSOLUTE DISABLED DATE RANGES) Configure absolute and relative disabled date ranges (no earlier than 1st January 2020, and no later than 3 days after today):
[https://whatsock.com/Templates/Datepickers/With%20Absolute%20Disabled%20Date%20Ranges/index.htm](https://whatsock.com/Templates/Datepickers/With%20Absolute%20Disabled%20Date%20Ranges/index.htm)

In the example above I digited in the input field 08/01/2007 and after I opened the picker. In this case the picker it will opens on the date 08/01/2007 and nothing at least on apparance/styles is selectable.

case 1) If I'm using the keyboard I can't navigate through years or months selection (both are disabled), so I can't change the date inside the piker.
case 2) if I'm using the mouse the years selection is disabled but I can change the months selection also if it is disabled and I will go directly to the max date or min date.

**Comment by impetoyt** [comment]
> Hi, thanks for reporting this. I've already pushed the fix for this in the latest download which can be tested here: https://whatsock.com/Templates/Datepickers/With%20Absolute%20Disabled%20Date%20Ranges/index.htm

I think there is another issue with this new fix, at this links:
[https://whatsock.com/Templates/Datepickers/Basic/index.htm](https://whatsock.com/Templates/Datepickers/Basic/index.htm)
[https://whatsock.com/Templates/Datepickers/Basic/index.htm](https://whatsock.com/Templates/Datepickers/Basic,%20ReadOnly%20Auto%20Open%20plus%20Disabled%20Ranges/index.htm)

I open the chrome console and I tried to use the presetDate method:
`$A("UniqueCalendarId").presetDate($A("UniqueCalendarId"), new Date("2021-07-13"), new Date("2021-07-03"), new Date("2021-07-23"));`

It will display the follow error message:
VM1040:10 Uncaught TypeError: Cannot read properties of undefined (reading 'month')
    at t.isDisabledDate (eval at success (4X.js:7:35961), <anonymous>:10:8810)
    at t.presetDate (eval at success (4X.js:7:35961), <anonymous>:10:10836)
    at <anonymous>:1:24



I debug a little in Datepicker.js, it's seems that the parameter `a` is undefined so when the code reach a.month or a.year it will give the error:
```
                isDisabledDate: function(e, t, n, a) {
                    a = a || e.range.current;
                    var r = e.range[a.month].disabled[a.year]
                      , o = e.range[a.month].disabled["*"]
                      , a = e.range[a.month].disabledWDays
                      , s = e.range.disabledWDays
                      , d = n.getDay();
                    return !!(r && -1 !== $A.inArray(t, r) || o && -1 !== $A.inArray(t, o) || a.length && -1 !== $A.inArray(d, a) || s.length && -1 !== $A.inArray(d, s) || e.isOutsideDateRange(n))
                },
```

**Comment by impetoyt** [comment]
I just opened the two page and calle the presetDate method without open the calendar or digit something in the input field
