### ISSUE TITLE
Calendar does not appear with invalid input field date 

### ISSUE THREAD

**Issue by impetoyt** [WhatSock/apex#49]
At this link:
[https://whatsock.com/Templates/Datepickers/Basic/index.htm](https://whatsock.com/Templates/Datepickers/Basic/index.htm)

1) without open the calendar just write something that isn't a date in the input field calendar like "sdwfg".
2) click on the button calendar. The calendar alendar does not appear and the error is display in the browser console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'disabled')
    at t.isDisabledDate (eval at success (4X.js:1:1), <anonymous>:10:8817)
    at t.isDisabledMonth (eval at success (4X.js:1:1), <anonymous>:10:8685)
    at t.isDisabledYear (eval at success (4X.js:1:1), <anonymous>:10:8571)
    at eval (eval at success (4X.js:1:1), <anonymous>:10:14162)
    at beforeRender (eval at success (4X.js:1:1), <anonymous>:10:14294)
    at Function.<anonymous> (4X.js:7:25606)
    at Function.loop (4X.js:7:30759)
    at i (4X.js:7:25585)
    at Function._parseDCScripts (4X.js:7:25881)
    at c (4X.js:7:74279)` 
3) clean the input field calendar and try to open the calendar again. Same error above.

**Comment by accdc** [comment]
Thanks, this issue has been corrected in Datepicker module 4.13.
